---
- name: Download repo key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
    dest: "{{ tailscale_keyring }}"
  tags:
    - tailscale

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ tailscale_keyring }}] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
    update_cache: True
    state: present
  tags:
    - tailscale

- name: Install required packages
  loop:
    - tailscale
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - tailscale

- name: Write default config
  notify:
    - Restart tailscale
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/tailscaled
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - tailscale

- name: Start tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - tailscale

- name: Write autoconnect script
  when: tailscale_authkey | default(False)
  ansible.builtin.template:
    src: script.j2
    dest: /usr/sbin/tailscaled-autoconnect
    owner: root
    group: root
    mode: u=rwx,g=,o=
  tags:
    - tailscale

- name: Write autoconnect service
  when: tailscale_authkey | default(False)
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/tailscaled-autoconnect.service
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - tailscale

- name: Start autoconnect service
  when: tailscale_authkey | default(False)
  ansible.builtin.systemd:
    name: tailscaled-autoconnect
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - tailscale

...
